kind = "web"
previewPath = "/"
title = "Hospital Management System"
version = "1.0.0"
id = "artifacts/hospital"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25045

[services.development]
run = "pnpm --filter @workspace/hospital run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/hospital", "run", "build" ]
publicDir = "artifacts/hospital/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25045"
BASE_PATH = "/"
